dnl This is a collection of general purpose macros

define(marker, <tr> <td height=8>MARK)dnl
define(marker1, <font color=red> Marker ONE </font>)dnl
define(marker2, <font color=red> Marker TWO </font>)dnl
define(IOCOMX, LORA WiFi)dnl
define(LORANAME, LORA WiFi)dnl
define(COLX, `#eeeeee')dnl

dnl for loop macro
define(`forloop',
       `pushdef(`$1', `$2')_forloop(`$1', `$2', `$3', `$4')popdef(`$1')')
define(`_forloop',
       `$4`'ifelse($1, `$3', ,
		   `define(`$1', incr($1))_forloop(`$1', `$2', `$3', `$4')')')

define(spacer, `
ifelse($1, , 8, $1)
<tr> <td height=ifelse($1, , 8, $1)>
space
')dnl
dnl