<script async>

    //console.log("Start LORA");
    const isNumeric2 = (str) => Number.isFinite(+str);

    function check_num(valxx, namex, lower, upper) {
        if (!isNumeric2(valxx))
            {
            alert("Field for " + namex + " must be a number.")
            return 0;
            }
        if (valxx < lower || valxx > upper)
            {
            alert("Number for " + namex + " is out of range.")
            return 0;
            }
        return 1;
        }
    function check_lims(data, validx, lower, upper) {
        return check_num(data.get(validx), validx, lower, upper)
        }
    async function save_lora() {
        //console.log("Save LORA");
        const formData = new FormData(myform);
        //console.log("Data", formData);
        if(!check_lims(formData, "spread", 6, 12)) return;
        if(!check_lims(formData, "bwidth", 10, 500)) return;
        if(!check_lims(formData, "txfreq", 433.05, 434.79)) return;
        if(!check_lims(formData, "deftrench", 0, 65534)) return;

        const plainFormData = Object.fromEntries(formData.entries());
        const jsonString = JSON.stringify(plainFormData);
        //console.log("Submitting: '%s'", jsonString);
        //document.getElementById("myform").submit();
        const response = await fetch("page_3.html", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: jsonString
                })
        const data = await response.text();
        //console.log("Data from lora config: " + data)
        const confButt = document.getElementById('confbutt');
        //console.log("butt:", confButt)
        confButt.value = data;
        }

    async function adj_recv_lora() {
        console.log("adj_recv_lora()");
        const rxButt = document.getElementById('rxbutt');
        const rxTune = document.getElementById('rxtune');
        if(!check_num(rxTune.value, "rxtune", -20000, 20000))
            return;
        const formData = new FormData(myform);
        formData.append("rxtune", rxTune.value);
        const plainFormData = Object.fromEntries(formData.entries());
        const jsonString = JSON.stringify(plainFormData);
        console.log("Submitting: '%s'", jsonString);
        const response = await fetch("page_3.html", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: jsonString
                })
        const data = await response.text();
        console.log("Data from lora tune: " + data)
        rxButt.value = data;
    }

    async function default_lora() {
        //console.log("default_lora()");
        const formData = new FormData(myform);
        formData.append("reset", "1");
        const plainFormData = Object.fromEntries(formData.entries());
        const jsonString = JSON.stringify(plainFormData);
        console.log("Submitting: '%s'", jsonString);
        //document.getElementById("myform").submit();
        const response = await fetch("page_3.html", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: jsonString
                })
        const data = await response.text();
        console.log("Data from lora reset: " + data)
        const defButt = document.getElementById('defbutt');
        defButt.value = data;

        // Fake reset config fields NOTE: change when code in chip changes
        document.getElementById('spread').value = 10;
        document.getElementById('bwidth').value = 50;
        document.getElementById('txpower').value = 12;
        document.getElementById('txfreq').value = 433.375;
    }
</script>

<table width=100%>

    <tr><td colspan=2>
    &nbsp; &nbsp; The following fields determine the LORA transmit / receive configuration.
    These configurations must match between the sender and receiver units.
    The parameters are range contained. The frequency parameter is a floating
    point number multiplied by megahertz. The bandwidth parameter is a floating
    point number multiplied by kilohertz. Please note: for communication
    stability the lowest recommended bandwidth is 40+ kHz. (This is due to the
    LORA Board's chrystal inaccuracy and / or instability) See the
    'Tune RX offset' section for more information.

    <tr><td colspan=2 align=center>
        <table align=center border=0 width=100%  frame=void>
            <tr><td colspan=3 width=100%>
                    <tr bgcolor=#eeeeee><td align=center>
                    <div style="font-size:large" align=center>
                    <b>LORA parameters:</b><br>
                    </div>
        </table>
        <tr><td>
        <tr> <td align=right>
            LORA Spread Factor: (6 - 12)  &nbsp
            <td width=50%><input id=spread name=spread type=text value=spreadspread>
        <tr><td align=right>
            LORA Bandwidth: (10 - 500) kHz &nbsp<td><input id=bwidth name=bwidth type=text
            value=bandbandbandband>
    <tr><td>
    <tr><td colspan=2 align=right>
        <table align=center border=0 width=100%  frame=void>
            <tr><td colspan=3 width=100%>
                    <tr bgcolor=#eeeeee><td align=center>
                    <div style="font-size:large" align=center>
                    <b>Optional (advanced) LORA parameters:</b><br>
                    </div>
        </table>
    <tr><td>
    <tr> <td align=right>
        LORA TX power (1-15):  &nbsp<td><input name=txpower id=txpower type=text
            value=txpowtxpowtxpow>
    <tr> <td align=right>
        LORA Frequency: (433.05 - 434.79) MHz &nbsp<td><input id=txfreq name=txfreq type=text
        value=freqfreqfreqfreqfreqfreq> <a href=channels.html >(Channel Table) </a>
    <tr><td colspan=3>
    <tr><td><td>
    <input type=button onclick=save_lora() id=confbutt name=confbutt
                                            value='Save LORA Configuration'>
    <tr> <td colspan=3 align=center>
        <table align=center border=0 width=100%  frame=void>
            <tr><td colspan=3 width=100%>
                    <tr bgcolor=#eeeeee><td align=center>
                    <div style="font-size:large" align=center>
                    <b>Tune LORA RX (receive) offset:</b><br>
                    </div>
        </table>
    <tr><td colspan=3>
    &nbsp; &nbsp; This field tunes the LORA receive frequency offset.
    This step is optional, and it may be necessary if communication
    is difficult at lower bandwidths. The tuning value can be derived from
    the Main LORA page's 'devi' field. The tuning value should be set to
    decrease the 'devi' field on the main page as close to zero as possible.
    The tuning value approximates the -devi/2. (minus (half devi)). For instance
    if devi is -10000 the tuning value should be 5000.
    <tr><td align=right>
        LORA RX tuning (+-) (0-10000):
                &nbsp<td><input id=rxtune type=text
                    value=rxtunerxtunerxtune>
    <tr><td><td>
    <input type=button onclick=adj_recv_lora() id=rxbutt
                                            value='Tune RX Frequency offset.'>
    <tr><td colspan=3>

    <tr> <td colspan=3 align=center>
        <table align=center border=0 width=100%  frame=void>
            <tr><td colspan=3 width=100%>
                    <tr bgcolor=#eeeeee><td align=center>
                    <div style="font-size:large" align=center>
                    <b>Reset LORA parameters:</b><br>
                    </div>
        </table>
    <tr><td colspan=3>
    &nbsp; &nbsp; The button below resets the LORA parameters to
    manufacturer's defaults. This may be necessary if communication
    configuration becomes out of sync with the target. Please remember
    to change these parameters for increased distance and increased privacy.
    Note that both the sender and receiver needs identical parameters to
    communicate. This action also resets the RX tuning.

    <tr><td><td>
    <input type=button onclick=default_lora() id=defbutt name=defbutt
                                            value='Reset LORA Parameters'>
    <tr><td colspan=3>

</table>
