<style>

.container {
  display: flex; /* Makes the container a flex container */
  //width: 100%;
  border-width: 0px;
}

.resdiv {
    border-style: solid;
    border-width: 1px;
    display: inline-block;
    vertical-align: top;
    horizontal-align: right;
    flex-grow: 1;
    overflow: auto;
    height: 200px;
}

</style>

<script async>

    //console.log("Start program");
    //alert("start");
    window.addEventListener('load', function() {
        //console.log("Start load");
        const checkInput = document.getElementById('prom');
        if (checkInput) {
            checkInput.addEventListener('change', checkprom , false);
        }
    document.querySelector('form').addEventListener('submit', (event) => {
        event.preventDefault();
        // Handle data manually here
        });
    });
    const isNumeric = (str) => Number.isFinite(+str);

    const truncateString = (str, num) => {
          if (str.length > num) {
            return str.slice(0, num) + "...";
          } else {
            return str;
          }
        };

    var escapeHTML = function(unsafe) {
      return unsafe.replace(/[&<>"']/g, function(m) {
        switch (m) {
          case '&':
            return '&amp;';
          case '<':
            return '&lt;';
          case '>':
            return '&gt;';
          case '"':
            return '&quot;';
          default:
            return '&#039;';
        }
      });
    };

    // Re - write in javascript
    function chksum(strx) {
        //console.log("chksum() strx='%s'", strx);
        let ret = 0;
        for(aa = 0; aa < strx.length; aa++)
            {
            nn = strx.charCodeAt(aa);
            //console.log(nn);
            qq = nn << 7 | nn;
            qq = qq & 0xffff;
            ret += qq + 10000;
            ret = ret & 0xffff;
            ret ^= 0x5aa5;
            ret = ret & 0xffff;
            }
        //console.log("sum ret=%s", ret.toString(16));
        return(ret);
    }

    // Pressed checkbox
    async function checkprom() {
        const checkInput = document.getElementById('prom');
        const chanInput = document.getElementById('chan');
        //console.log("Check pressed", checkInput.checked)
        if (!chanInput.value)
            return;
        jsonString = '{"check": ' + checkInput.checked + ', "chan": "'
                        + chanInput.value +  '" }';
        redo_timer();
        const response = await fetch("post.html", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: jsonString
                })
    }
    function check_number(valx, lower, upper) {

        if (valx < lower || valx > upper)
            {
            alert("Trench number out of range.");
            return 0;
            }
        return 1;
        }

    async function pressed_sub() {
        // Check parameters
        const textInput = document.getElementById('txt');
        const chanInput = document.getElementById('chan');

        if (chanInput.value == "")
            chanInput.value = 0;       // Auto zero
        if (!isNumeric(chanInput.value))
            {
            alert("Cannot submit a non number for trench ");
            textInput.focus();
            return;
            }
        if (!check_number(chanInput.value, 0, 0xffff))
            {
            return;
            }
        if (textInput.value == "")
            {
            //console.log("Empty string. Not Submitting");
            alert("Cannot submit empty message.");
            textInput.focus();
            return;
            }
        textInput.value = escapeHTML(textInput.value);
        const formData = new FormData(myform);
        const plainFormData = Object.fromEntries(formData.entries());
        if(plainFormData['text'].length > 230)
            {
            alert("Truncating message to 230 bytes");
            plainFormData['text'] = truncateString(plainFormData['text'], 230);
            }
        textInput.disabled = true

        const num = chksum(plainFormData['text']);
        plainFormData['hash'] = num.toString(16);
        //plainFormData['answer'] = "Awaiting ...";
        const jsonString = JSON.stringify(plainFormData);

        //console.log("Submitting '%s'", jsonString);
        const response = await fetch("post.html", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: jsonString
                })
        const data = await response.text();
        //console.log("Data from await: '%s'", data);

        // Fill in current state
        const textOutput = document.getElementById('current');
        textOutput.innerHTML = data;
        setTimeout(updateLiveData, 1000);
    }

function textUpdate() {
    const textInput = document.getElementById('txt');
    //console.log('Text area content changed in real-time.' +
    //                 textInput.value.length);
    const cntOutput = document.getElementById('cnt');
    cntOutput.innerHTML = "Count: " + textInput.value.length;
}

function chanUpdate() {
    checkprom();
}

window.addEventListener('load', () => {
    const textInput = document.getElementById('txt');
    textInput.addEventListener('input', textUpdate)
    const chanInput = document.getElementById('chan');
    chanInput.addEventListener('input', chanUpdate)
    const cntOutput = document.getElementById('cnt');
    cntOutput.innerHTML = "Count: " + textInput.value.length;
});

window.addEventListener("keydown", onKeyDown, true);
window.addEventListener("keyup", onKeyUp, true);

ctrl = 0;
function onKeyDown(e){
    //console.log("Dn " + e.key);
    if(e.key == "Enter" && ctrl == 1)
        {
        const textInput = document.getElementById('txt');
        //console.log("Ctrl-Enter: '%s'", textInput.value )
        //e.preventDefault();
        pressed_sub();
        }
    if(e.key == "Control")
        {
        ctrl = 1
        }
    else
        {
        ctrl = 0
        }
  }
function onKeyUp(e){
    //console.log("Up " + e.key);
    if(e.key == "Control")
        {
        ctrl = 0
        }
  }
</script>

<table align=center width=100% padding=1>

    <tr><td> Data: <td colspan=3>
        <div class="container">
            <div class=resdiv id=hist> Nothing received yet ... &nbsp; </div>
        </div>
    <tr><td>
        Trench:
        <td><input type=text name=chan id=chan value=trenchtrenchtrench> (0-65534)
        <td>
        <input type=checkbox name=prom id=prom>
        <label for="prom">Show all trenches</label>
        <td> &nbsp;
    <tr><td>
        Send:
        <td colspan=2>
        <textarea autofocus name=text rows=4 cols=64 id=txt></textarea>
        <td align=center>
                          <div id=cnt>Count: 0</div>
                          <i>Max 230 Characters</i><br>
                          Ctrl-Enter to submit <p>
            <input type=button value=Send onclick=pressed_sub()><br>
            <div id=status></div>
    <tr><td>
        Status:
        <td class=mydiv>
            <div class=mytext id=current>Idle.</div>
        <td class=mydiv colspan=2>
            <table width=100%>
                <td class=mydiv>
                    <div class=mytext id=rssi> Last RSSI: 0
                    </div>
                <td class=mydiv>
                    <div class=mytext id=devi> Last devi: 0
                    </div>
                <td class=mydiv>
                    <div class=mytext id=ppm> Last PPM: 0
                    </div>
            </table>
</table>
