<script async>

    function containsPunctuation(strz) {
        // Regex to match a variety of common punctuation marks
        const punctuationRegex = /[!"#$%&'()*,\./:;<=>?@[\\^`{|}\\]~]/;
        return punctuationRegex.test(strz);
    }
    async function save_wifi() {
        //console.log("Save WIFI");
        const formData = new FormData(myform);
        //console.log("formData", formData);
        if(containsPunctuation(formData.get("apname")))
            {
            alert("Wifi hostname cannot contain punctuation.")
            return;
            }
        if(formData.get("appass") != formData.get("appass2"))
            {
            alert("Wifi passes must match.")
            return;
            }
        if(formData.get("appass").length < 8)
            {
            alert("Wifi pass must be 8 letters or longer.")
            return;
            }
        const plainFormData = Object.fromEntries(formData.entries());
        const jsonString = JSON.stringify(plainFormData);
        //console.log("Submitting: '%s'", jsonString);
        //document.getElementById("myform").submit();

        const response = await fetch("page_2.html", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: jsonString
                })
        const data = await response.text();
        const confButt = document.getElementById('netbutt');
        //console.log("netbutt:", confButt)
        confButt.value = data;
        const confReboot = document.getElementById('reboot');
        confReboot.innerHTML = "Please reboot device for settings to take effect.";
    }
</script>

<table width=100%>

    <tr><td colspan=2 align=center height=12>
    The following fields determine the Station Name and Password of this LORANAME.
    The device will appear on your WiFI network by this name. For safety and security,
    the LORANAME must be configured with a password. The password needs to be at
    least <font color=#0000bb> 8 characters</font>
    or longer. Please avoid using space, punctuation marks and non ASCII characters.<br>
    You may use the _ (underscore) - (minus) sign + (plus) sign.
    <tr><td colspan=2 align=center>
        <table align=center border=0 width=100%  frame=void>
            <tr><td colspan=3 width=100%>
                    <tr bgcolor=#eeeeee><td align=center>
                    <div style="font-size:large" align=center>
                    <b>New Web Login Credentials:</b><br>
                    </div>
        </table>
        <tr><td>
        <tr> <td align=right>
    Station name:  &nbsp<td width=50%><input id=apname name=apname type=text
                        autofocus value=hnamehnamehnamehnamehnamehnamehname>
        <tr><td align=right>
    Station password:  &nbsp<td><input name=appass type=password
                        value=pass1pass1pass1pass1pass1pass1>
        <tr><td align=right>
    Repeat password:  &nbsp<td><input name=appass2 type=password
                        value=pass2pass2pass2pass2pass2pass2>
    <tr><td colspan=3>
    <hr>
    <tr> <td> <td colspan=2>
        <input type=button onclick=save_wifi() id=netbutt name=netbutt accesskey=c
        value='Save Web Configuration'>
                        <font style=color:#aaaaaa>(Alt+Shift+c)</font>

    <tr> <td colspan=3 align=center>

</table>