include(mac/general.mac)
include(mac/cntlines.mac)

    <table align=center border=0 width=100% >
        <tr bgcolor=#aaffaa><td align=center colspan=3>
            <div style="font-size:large" align=center>
                <b>Relays Status:&nbsp  </b>
            </div>
        <tr> <td>
        <tr><td>
            &nbsp; The relay's field is gray when Idle / OFF and Orange colored when Active / ON.
            The relay status here follows the physical relay's state, after routing has calculated
            which relay to activate / de-activate.

    </table>
    <table align=center border=0 width=100% frame=void cellspacing=10, cellpadding=4>
        <tr bgcolor=#eeeeee>
        <th> Relay 1
        <th> Relay 2
        <th> Relay 3
        <th> Relay 4
        RELAYLINE(0, `#bbbbbb', OFF)
    </table>





