include(mac/general.mac)
include(mac/cntlines.mac)

    <tr bgcolor=#aaffaa><td align=center colspan=3>
    <div style="font-size:large" align=center>
        <b>Alert configurations:&nbsp  </b>
    </div>

    <tr><td colspan=2>
    <table align=center border=0 width=100% padding=10>
    <tr> <td>
    <tr><td colspan=6 >
        &nbsp; The alert will sound if the counter exceeds a specified value.
        The alert will sound if the counter exceeds a specified value.
        The alert will sound if the counter exceeds a specified value.

    <tr><td height=8>
    <table width=100%>
    <tr>
        <th align=center> Input #
        <th align=center> Input Name
        <th align=center> Alert at Count
        <th align=center> Enable<br>Count Alert
        <th align=center> Alert at Hours
        <th align=center> Enable<br>Time Alert

    ALARMLINE(1, `#eeeeee', xxxxxxxxxx, checked, yyyyyyyyyy, not)
    ALARMLINE(2, `#eeeeee', xxxxxxxxxx, not,     yyyyyyyyyy, checked)
    ALARMLINE(3, `#eeeeee', xxxxxxxxxx, checked, yyyyyyyyyy, not)
    ALARMLINE(4, `#eeeeee', xxxxxxxxxx, not,     yyyyyyyyyy, checked)
    ALARMLINE(5, `#eeeeee', xxxxxxxxxx, checked, yyyyyyyyyy, not)
    ALARMLINE(6, `#eeeeee', xxxxxxxxxx, not,     yyyyyyyyyy, checked)
    ALARMLINE(7, `#eeeeee', xxxxxxxxxx, checked, yyyyyyyyyy, not)
    ALARMLINE(8, `#eeeeee', xxxxxxxxxx, not,     yyyyyyyyyy, checked)

    </table>

