<style>

.container {
  display: flex; /* Makes the container a flex container */
  //width: 100%;
  border-width: 0px;
}

.resdiv {
    border-style: solid;
    border-width: 1px;
    display: inline-block;
    vertical-align: top;
    horizontal-align: right;
    flex-grow: 1;
    overflow: auto;
    height: 300px;
}

</style>

<script async>

    //console.log("Start program");
    //alert("start");

    const isNumeric = (str) => Number.isFinite(+str);

    const truncateString = (str, num) => {
          if (str.length > num) {
            return str.slice(0, num) + "...";
          } else {
            return str;
          }
        };

    // re - write in javascript
    function chksum(strx) {
        //console.log("chksum() strx='%s'", strx);
        let ret = 0;
        for(aa = 0; aa < strx.length; aa++)
            {
            nn = strx.charCodeAt(aa);
            //console.log(nn);
            qq = nn << 7 | nn;
            qq = qq & 0xffff;
            ret += qq + 10000;
            ret = ret & 0xffff;
            ret ^= 0x5aa5;
            ret = ret & 0xffff;
            }
        //console.log("sum ret=%s", ret.toString(16));
        return(ret);
    }

     async function pressed_sub() {
        // Check parameters
        const textInput = document.getElementById('txt');
        if (textInput.value == "")
            {
            //console.log("Empty string. Not Submitting");
            alert("Cannot submit empty message.");
            textInput.focus();
            return;
            }
        const chanInput = document.getElementById('chan');
        if (!isNumeric(chanInput.value))
            {
            alert("Cannot submit a non number for channel " + chanInput.value);
            textInput.focus();
            return;
            }
        const formData = new FormData(myform);
        const plainFormData = Object.fromEntries(formData.entries());
        if(plainFormData['text'].length > 200)
            {
            alert("Truncating message to 200 bytes");
            }
        plainFormData['text'] = truncateString(plainFormData['text'], 200);
        const num = chksum(plainFormData['text']);
        plainFormData['hash'] = num.toString(16);
        //plainFormData['answer'] = "Awaiting ...";
        const jsonString = JSON.stringify(plainFormData);

        //console.log("Submitting '%s'", jsonString);
        const response = await fetch("post.html", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: jsonString
                })
        const data = await response.text();
        //console.log("Data from await: '%s'", data);

        // Fill in current state
        const textOutput = document.getElementById('current');
        textOutput.innerHTML = data;
    }

    function pressed_send() {
        //const mForm = document.getElementById('myform')
        //mForm.submit()
        pressed_sub();
    }

function textUpdate() {
    const textInput = document.getElementById('txt');
    //console.log('Text area content changed in real-time.' +
    //                 textInput.value.length);
    const cntOutput = document.getElementById('cnt');
    cntOutput.innerHTML = "Count: " + textInput.value.length;
}

window.addEventListener('load', () => {
    const textInput = document.getElementById('txt');
    textInput.addEventListener('input', textUpdate)
    const cntOutput = document.getElementById('cnt');
    cntOutput.innerHTML = "Count: " + textInput.value.length;
});

window.addEventListener("keydown", onKeyDown, true);
window.addEventListener("keyup", onKeyUp, true);

ctrl = 0;
function onKeyDown(e){
    //console.log("Dn " + e.key);
    if(e.key == "Enter" && ctrl == 1)
        {
        const textIn = document.getElementById('txt');
        //console.log("Ctrl-Enter: '%s'", textIn.value )
        e.preventDefault();
        pressed_send();
        }
    if(e.key == "Control")
        {
        ctrl = 1
        }
    else
        {
        ctrl = 0
        }
  }
function onKeyUp(e){
    //console.log("Up " + e.key);
    if(e.key == "Control")
        {
        ctrl = 0
        }
  }
</script>

<table align=center width=100% padding=10>

    <tr><td> Sent / Received: <td colspan=2>
        <div class="container">
            <div class=resdiv id=hist> Nothing received yet ... &nbsp; </div>
        </div>
    <tr><td class=mydiv>
        Trench:
        <td><input type=text name=chan id=chan value=trenchtrenchtrench> (0-65534)
        <td>
    <tr><td class=mydiv>
        Send:
        <td>
        <textarea autofocus name=text rows=4 cols=64 id=txt></textarea>
        <td align=center>
                          <div id=cnt>Count: 0</div>
                          <i>Max 200 Characters</i><br>
                          Ctrl-Enter to submit <p>
            <input type=button value=Send onclick=pressed_send()><br>
            <div id=status></div>

    <tr><td class=mydiv>
        Send Status:
        <td colspan=2>
        <div class=mytext width=90% id=current>Idle.<br></div>

</table>
