include(mac/cntlines.mac)
    <tr> <td height=8>
    <table align=center border=0 width=100% frame=void>
    <tr><td colspan=2 width=100%>
        <tr bgcolor=#aaffaa><td align=center>
            <div style="font-size:large" align=center>
                <b>Temperature Sensor Friendly Names:</b><br>
            </div>
    </table>

    <tr> <td>
    &nbsp; &nbsp; &nbsp; The sensors can be named to reflect the device it is monitoring.
    The name can be 24 characters long. Please avoid foreign characters and punctuation marks.<br>
    An example of a name could be "Motor 4 Temp"

    <tr> <td height=8>

    <table align=center border=0 width=100% frame=void>

    <tr bgcolor=#bbbbbb>
        <th align=center> Input Number
        <th align=center> Name
        <th align=center> Friendly Sensor Name

        TMPNLINE(1, `#eeeeee')
        TMPNLINE(2, `#dddddd')

    </table>

    <tr> <td colspan=3 align=center>
    <hr>
    <tr><td colspan=3 align=center>
    <input type=submit name=config value='Save Temp. Sensor Names'>







