
/* =====[ ESP32 project ]=================================================

   File Name:       main/html/channels.html

   Description:     Main file

   Revisions:       (for the original file)

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  Sun, 29-03-26   Peter Glen      Initial version.

   ======================================================================= */

// Page contents as header. DO NOT EDIT. Contents are overwritten at
// compile time.
// Edit the corresponding HTML file instead: main/html/channels.html

const char lora_chann_html [] =

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n"
"<html>\n"
"<head>\n"
"<title>LORA WiFi LORA Channel Allocation Page</title>\n"
"<meta charset=\"UTF-8\">\n"
"<link rel='icon' href='data:;base64,iVBORw0KGgo='>\n"
"</head>\n"
"<body>\n"
"<form method=post id=myform>\n"
"<table align=center border=0 width=800 frame=void>\n"
"<style>\n"
".container {\n"
"	text-align: left;\n"
"	border: 1px solid green;\n"
"	padding: 5px;\n"
"    }\n"
".container table {\n"
"	border: 1px solid red;\n"
"    margin: 0 auto;\n"
"    }\n"
".chris {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      38px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      34px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2a  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2b  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2c  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris3  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      16px;\n"
"    }\n"
".myDiv {\n"
"  font-size: 100px;\n"
"  text-align: center;\n"
"}\n"
"html, address, blockquote, body, dd, div, dl, dt, fieldset,\n"
"form, h1, h2, h3, h4, h5, h6, noframes, ol, p, ul, center,\n"
"dir, hr, menu, pre {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    }\n"
".mydiv {\n"
"    /*background:yellow;\n"
"    color:blue;\n"
"    border-style:solid;\n"
"    border-width:medium;\n"
"    display:inline-block;\n"
"    */\n"
"    vertical-align:top;\n"
"    horizontal-align:right;\n"
"}\n"
"textarea {\n"
"    border-color:#eeeeee;\n"
"    width:90%;\n"
"}\n"
".mytext {\n"
"    /*background:yellow;\n"
"    color:blue;*/\n"
"    width:100%;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:#eeeeee;\n"
"    display:inline-block;\n"
"}\n"
".rebootstat {\n"
"    font-size:  16px;\n"
"    color:      red;\n"
"}\n"
".statstat {\n"
"    font-size:  16px;\n"
"    color:      blue;\n"
"}\n"
"    </style>\n"
"</style>\n"
" <tr><td>\n"
"    <table width=100% border=0>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"    <a href=page_1.html?home=true style=\"text-decoration: none; color: black;\">\n"
"        <div class=\"chris\" align=center>\n"
"            LORA WiFi Transceiver\n"
"        </div>\n"
"    </a>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div id=status class=statstat align=center>\n"
"            StatusStatusStatusStatusStatusStatusStatusStatus\n"
"        </div>\n"
"    </table>\n"
"<table width=100%>\n"
"    <td align=justify height=12>\n"
"    &nbsp; &nbsp; The following table describes the LORA 433 MHz channel allocation,\n"
"    recommended by the manufacturer of the device and international standard bodies.\n"
"    In the LORA WiFi product, these values are not enforced, they can be set to\n"
"    arbitrary values. The only criteria is that they are between the\n"
"    device's lower and upper frequency limits.\n"
"    Please note that both the receiver and sender has to be tuned to the\n"
"    same frequency to communicate.\n"
"    <tr><td>\n"
"    <tr><td> <font style=font-size:x-large>\n"
"                <b>Common recommended platform presets:</b></font>\n"
"    <tr><td>\n"
"    <table width=80% align=center>\n"
"        <tr align=center>\n"
"            <td><b>LORA Channel</b>\n"
"            <td><b>Frequency</b>   <td><b>Bandwidth (optional)</b> <td><b>Scope</b>\n"
"        <tr align=center>\n"
"            <td width=10% align=center>1\n"
"            <td>433.375 MHz   <td>125 kHz  <td>Default / Mandatory\n"
"        <tr  align=center bgcolor=#eeeeeeff>\n"
"            <td width=10% align=center>2\n"
"            <td>433.575 MHz   <td>125 kHz  <td>Default / Mandatory\n"
"        <tr align=center >\n"
"            <td width=10% align=center>3\n"
"            <td>433.775 MHz   <td>125 kHz  <td>Optional / Extension\n"
"        <tr  align=center bgcolor=#eeeeeeff>\n"
"            <td width=10% align=center>4\n"
"            <td>433.975 MHz   <td>125 kHz  <td>Optional / Extension\n"
"        <tr align=center >\n"
"            <td width=10% align=center>5\n"
"            <td>434.175 MHz   <td>125 kHz  <td>Optional / Extension\n"
"        <tr  align=center bgcolor=#eeeeeeff>\n"
"            <td width=10% align=center>6\n"
"            <td>434.375 MHz   <td>125 kHz  <td>Optional / Extension\n"
"        <tr align=center >\n"
"            <td width=10% align=center>7\n"
"            <td>434.575 MHz   <td>125 kHz  <td>Optional / Extension\n"
"    </table>\n"
" <tr><td>\n"
" The device's frequency defaults to channel 1. (433.375 MHz).<p>\n"
" <tr><td><font style=font-size:x-large>\n"
"    <b>Bandwidth threshold values:</b>\n"
" <tr><td>\n"
"    <table width=80% align=center>\n"
"        <tr><td>7.8kHz     10.4kHz    15.6kHz    20.8kHz\n"
"        31.25kHz    41.7kHz    62.5kHz    125kHz    250kHz   500kHz\n"
"    </table>\n"
"<tr><td>\n"
"The bandwidth configuration will obey the above thresholds, and set according\n"
"to the limit specified on the above table. For example setting it 40kHz will\n"
"round it down to 31.32kHz. Set it to 42kHz will round it down ro 41.4kHz.<p>\n"
"<tr><td>\n"
" The device bandwidth defaults to 40kHz.<p>\n"
"**Disclaimer: While the 433MHz Band is regulated relatively uniformly across\n"
"countries, still, the regulations vary somewhat. Always check local spectrum regulations\n"
"before deploying 433MHz devices.<p>\n"
"<tr><td>\n"
"  <table width=100% border=0>\n"
"        <tr>\n"
"            <td align=center colspan=3 width=100%>\n"
"            <hr>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_4.html> Main Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_2.html> WiFi Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                 <div style=\"font-size:large\"   align=center>\n"
"                    <a href=page_3.html> LORA Parameters </a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                    <a href=page_8.html> Quick Start Manual </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html> Back to Home Page </a>\n"
"                </div>\n"
"           <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html?reboot=true>Reboot Device</a>\n"
"                </div>\n"
"    </table>\n"
"    <tr>\n"
"    <td colspan=2 align=center>\n"
"    <hr>\n"
"    <!--<tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <a href=page_1.html?home=true>Back to Home Page</a>\n"
"        </div>\n"
"    -->\n"
"    <tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:small\">\n"
"            ID (Main) (Mac Address): macmacmacmacmacmacmac<br>\n"
"            Current Boot Count:  bcountbcount<br>\n"
"            Software Version / Build Date: softversoftversoftversoftversoftversoftver<br>\n"
"        </div>\n"
"    <tr><td colspan=2 align=center>\n"
"        Peter Glen, (C) 2026 <br>\n"
"    <tr><td colspan=2 align=center>\n"
"</table>\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
// EOF
