
/* =====[ ESP32 project ]=================================================

   File Name:       main/html/page_8.html

   Description:     Main file

   Revisions:       (for the original file)

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  Tue, 24-03-26   Peter Glen      Initial version.

   ======================================================================= */

// Page contents as header. DO NOT EDIT. Contents are overwritten at
// compile time.
// Edit the corresponding HTML file instead: main/html/page_8.html

const char manual_html [] =

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n"
"<html>\n"
"<head>\n"
"<title>LORA WiFi User Manual</title>\n"
"<meta charset=\"UTF-8\">\n"
"<link rel='icon' href='data:;base64,iVBORw0KGgo='>\n"
"</head>\n"
"<body>\n"
"<form method=post id=myform>\n"
"<table align=center border=0 width=800 frame=void>\n"
"<style>\n"
".container {\n"
"	text-align: left;\n"
"	border: 1px solid green;\n"
"	padding: 5px;\n"
"    }\n"
".container table {\n"
"	border: 1px solid red;\n"
"    margin: 0 auto;\n"
"    }\n"
".chris {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2a  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2b  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2c  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris3  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      16px;\n"
"    }\n"
".myDiv {\n"
"  font-size: 100px;\n"
"  text-align: center;\n"
"}\n"
"html, address, blockquote, body, dd, div, dl, dt, fieldset,\n"
"form, h1, h2, h3, h4, h5, h6, noframes, ol, p, ul, center,\n"
"dir, hr, menu, pre {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    }\n"
".mydiv {\n"
"    /*background:yellow;\n"
"    color:blue;\n"
"    border-style:solid;\n"
"    border-width:medium;\n"
"    display:inline-block;\n"
"    */\n"
"    vertical-align:top;\n"
"    horizontal-align:right;\n"
"}\n"
"textarea {\n"
"    border-color:#eeeeee;\n"
"    width:90%;\n"
"}\n"
".mytext {\n"
"    /*background:yellow;\n"
"    color:blue;*/\n"
"    width:100%;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:#eeeeee;\n"
"    display:inline-block;\n"
"}\n"
".rebootstat {\n"
"    font-size:  16px;\n"
"    color:      red;\n"
"}\n"
".statstat {\n"
"    font-size:  16px;\n"
"    color:      blue;\n"
"}\n"
"    </style>\n"
"</style>\n"
"<tr><td>\n"
"    <table width=100% border=0>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"    <a href=page_1.html?home=true style=\"text-decoration: none; color: black;\">\n"
"        <div class=\"chris\" align=center>\n"
"            LORA WiFi Transceiver\n"
"        </div>\n"
"    </a>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div id=status class=statstat align=center>\n"
"            StatusStatusStatusStatusStatusStatusStatusStatus\n"
"        </div>\n"
"    </table>\n"
"<table width=100%>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi transceiver (transmitter / receiver) is a long range\n"
"    pier to pier communcation device.\n"
"    In the paragraphs below, a quick description of the\n"
"    device's configuration and operation is detailed.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Communcation</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi is ready to communicate out of the box; Just plug\n"
"    it in to any USB, and connect to its web page. One may connect with any\n"
"    standard browser, a phone, tablet, computer, or any other browser capable\n"
"    device. Once connected, use the provided text box to send a message.\n"
"    The message should show up on the other device, configured to the same trench\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Quick Setup, Connecting</b>\n"
"        </div>\n"
"    <tr><td   style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; Connecting to the LORA WiFi device via the web interface is easy.\n"
"    On your Browser device (cell phone / computer etc.) connect to the WiFi\n"
"    Station named LoraWiFi-NNNN (where NNNN is a four digit number of the device)\n"
"    and use the password '12345678' (without the quotes).\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>The Trench parameter</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The trench is a distinct communication sub entry within the\n"
"    current transmission channel. To communicate between two devices, their trench\n"
"    numbers must match. (Naturally, all other LORA parameters must match as well)\n"
"    The LORA WiFi system comes set to trench zero, channel 1 from the\n"
"    manufacturer. Should a different trench be needed, the process extremely simple: just\n"
"    enter a new trench number in the 'Trench:' text field. The trench number\n"
"    can be from 0 to 65534. Both the receiver and transmitter has to be on the\n"
"    same trench.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Trench Safety</b>\n"
"        </div>\n"
"    <tr><td   style=\"text-align:justify;\">\n"
"        &nbsp; &nbsp; The device comes configured at trench 0. This is\n"
"        meant to be a test channel for initial communication. It is\n"
"        recommended to change the trench number after successfully testing\n"
"        communication.Both the receiver and transmitter has to have the\n"
"        trench and the same LORA parameters.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Device Configuration Reset</b>\n"
"        </div>\n"
"    <tr><td   style=\"text-align:justify;\">\n"
"        &nbsp; &nbsp; If one encounters any difficulty during the pairing process,\n"
"        the device parameters may be reset to their initial values by holding down\n"
"        the configuration button during power up. This will reset device\n"
"        configuration to manufacturer's defaults. (On the waterproof version hold\n"
"        a magnet to the reed switch while powering up)\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Quick Setup, Default Configuration</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi system starts up in transmit / receive mode\n"
"    on channel 0. One may connect to the device's web page to use it and\n"
"    to configure it. If no communication activity occurs in one minute,\n"
"    the device will terminate the configuration mode, and resume communication\n"
"    mode.\n"
"<tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Features, Encryption and Checksum</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi system communicates with an unencrypted data stream.\n"
"    However, the data is protected with a checksum. Data cannot be falsified\n"
"    by external sources, as the LORA WiFi will reject packets with an invalid\n"
"    checksum. If one desires extra secrecy, there are plenty of applications\n"
"    that serve this purpose on the browser / text entry level. However, tweaking\n"
"    the LORA parameters may serve as a good substitute, as guessing the correct\n"
"    LORA parameters and trench number can be as challenging as breaking encryption.\n"
"<tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Distance expectations</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi system utilizes a SEMTEC LORA device. The LORA\n"
"     device's specification suggest an 8-10 kilometer (line of sight) range.\n"
"     Under ideal conditions, this can be measured and proven with this\n"
"     implementation, and it delivers according to specification. Using\n"
"     the device in a non line of sight configuration, the range is\n"
"     significantly less. For instance using in highrise building area, the\n"
"     range can be as little as 500 meters.\n"
"    <br>\n"
"</table>\n"
"<tr><td>\n"
"  <table width=100% border=0>\n"
"        <tr>\n"
"            <td align=center colspan=3 width=100%>\n"
"            <hr>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_4.html> Main Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_2.html> WiFi Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                 <div style=\"font-size:large\"   align=center>\n"
"                    <a href=page_3.html> LORA Parameters </a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                    <a href=page_8.html> Quick Start Manual </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html> Back to Home Page </a>\n"
"                </div>\n"
"           <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html?reboot=true>Reboot Device</a>\n"
"                </div>\n"
"    </table>\n"
"    <tr>\n"
"    <td colspan=2 align=center>\n"
"    <hr>\n"
"    <!--<tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <a href=page_1.html?home=true>Back to Home Page</a>\n"
"        </div>\n"
"    -->\n"
"    <tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:small\">\n"
"            ID (Main) (Mac Address): macmacmacmacmacmacmac<br>\n"
"            Current Boot Count:  bcountbcount<br>\n"
"            Software Version / Build Date: softversoftversoftversoftversoftversoftver<br>\n"
"        </div>\n"
"    <tr><td colspan=2 align=center>\n"
"        Peter Glen, (C) 2026 <br>\n"
"    <tr><td colspan=2 align=center>\n"
"</table>\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
// EOF
