
/* =====[ ESP32 project ]=================================================

   File Name:       main/html/page_1.html

   Description:     Main file

   Revisions:       (for the original file)

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  Sun, 05-04-26   Peter Glen      Initial version.

   ======================================================================= */

// Page contents as header. DO NOT EDIT. Contents are overwritten at
// compile time.
// Edit the corresponding HTML file instead: main/html/page_1.html

const char index_html [] =

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n"
"<html>\n"
"<head>\n"
"<title>LORAWIFI Main Page</title>\n"
"<meta charset=\"UTF-8\">\n"
"<link rel='icon' href='data:;base64,iVBORw0KGgo='>\n"
"</head>\n"
"<body>\n"
"<form method=post id=myform>\n"
"<table align=center border=0 width=800 frame=void>\n"
"<style>\n"
".container {\n"
"	text-align: left;\n"
"	border: 1px solid green;\n"
"	padding: 5px;\n"
"    }\n"
".container table {\n"
"	border: 1px solid red;\n"
"    margin: 0 auto;\n"
"    }\n"
".chris {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      38px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      34px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2a  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2b  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2c  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris3  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      16px;\n"
"    }\n"
".myDiv {\n"
"  font-size: 100px;\n"
"  text-align: center;\n"
"}\n"
"html, address, blockquote, body, dd, div, dl, dt, fieldset,\n"
"form, h1, h2, h3, h4, h5, h6, noframes, ol, p, ul, center,\n"
"dir, hr, menu, pre {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    }\n"
".mydiv {\n"
"    /*background:yellow;\n"
"    color:blue;\n"
"    border-style:solid;\n"
"    border-width:medium;\n"
"    display:inline-block;\n"
"    */\n"
"    vertical-align:top;\n"
"    horizontal-align:right;\n"
"}\n"
"textarea {\n"
"    border-color:#eeeeee;\n"
"    width:90%;\n"
"}\n"
".mytext {\n"
"    /*background:yellow;\n"
"    color:blue;*/\n"
"    width:100%;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:#eeeeee;\n"
"    display:inline-block;\n"
"}\n"
".rebootstat {\n"
"    font-size:  16px;\n"
"    color:      red;\n"
"}\n"
".statstat {\n"
"    font-size:  16px;\n"
"    color:      blue;\n"
"}\n"
"    </style>\n"
"</style>\n"
"<tr><td>\n"
"    <table width=100% border=0>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"    <a href=page_1.html?home=true style=\"text-decoration: none; color: black;\">\n"
"        <div class=\"chris\" align=center>\n"
"            LORA WiFi Transceiver\n"
"        </div>\n"
"    </a>\n"
"    </table>\n"
"<script async>\n"
"timeoutID = 0;\n"
"window.addEventListener('load', function()\n"
"{\n"
"    //console.log(\"load window\");\n"
"    var xhr = null;\n"
"    getXmlHttpRequestObject = function()\n"
"    {\n"
"        if(!xhr)\n"
"        {\n"
"            // Create a new XMLHttpRequest object\n"
"            xhr = new XMLHttpRequest();\n"
"        }\n"
"        return xhr;\n"
"    };\n"
"    updateLiveData = function()\n"
"    {\n"
"        var url = 'live.html'\n"
"        var xhr3 = getXmlHttpRequestObject();\n"
"        xhr3.onreadystatechange = evenHandler;\n"
"        xhr3.open(\"GET\", url, true);\n"
"        xhr3.send(null);\n"
"    };\n"
"    updateLiveData();\n"
"    let sentx = \"\";\n"
"    function evenHandler()\n"
"    {\n"
"        timeoutID = 0;\n"
"        //console.log(\"Answer %d %d '%s' \",\n"
"        //        xhr.readyState, xhr.status, xhr.responseText);\n"
"        // Check response is ready or not\n"
"        if(xhr.readyState == 4 && xhr.status == 200)\n"
"            {\n"
"            if(xhr.responseText == \"\")\n"
"                {\n"
"                // Update the live data every xx msec\n"
"                setTimeout(updateLiveData, 1000);\n"
"                return;\n"
"                }\n"
"            //console.log(\"Answer %d %d '%s' \",\n"
"            //            xhr.readyState, xhr.status, xhr.responseText);\n"
"            const jsObject = JSON.parse(xhr.responseText);\n"
"            const statInput = document.getElementById('current');\n"
"            const textInput = document.getElementById('txt');\n"
"            statInput.innerHTML = jsObject.strx;\n"
"            //console.log(\"Answer: '\" + jsObject.strx +\n"
"            //                \"' Update:\" + jsObject.update +\n"
"            //                        \" Count: \", + jsObject.count);\n"
"            // Update text control states\n"
"            if(jsObject.strx == \"Done\")\n"
"                {\n"
"                textInput.disabled = false;\n"
"                const cntOutput = document.getElementById('cnt');\n"
"                cntOutput.innerHTML = \"Count: 0\"\n"
"                textInput.focus();\n"
"                textInput.style.cursor = \"auto\";\n"
"                }\n"
"            else if (jsObject.strx == \"Timeout\")\n"
"                {\n"
"                textInput.disabled = false;\n"
"                textInput.focus();\n"
"                }\n"
"            else if (jsObject.strx == \"Idle ...\")\n"
"                {\n"
"                textInput.disabled = false;\n"
"                //textInput.focus();\n"
"                }\n"
"            if (jsObject.sent)\n"
"                {\n"
"                //console.log(\"sent %d '%d' \", xhr.status, jsObject.sent);\n"
"                }\n"
"            if (jsObject.update)\n"
"                {\n"
"                textInput.value = \"\";\n"
"                sentx = \"\";\n"
"                for(aa = 0; aa < jsObject.maxcnt; aa++)\n"
"                    {\n"
"                    let curr = \"hist_\" + aa;\n"
"                    if (jsObject[curr])\n"
"                        {\n"
"                        //console.log(\"sent hist %d %s = '%s' \",\n"
"                        //                        xhr.status, curr, jsObject[curr]);\n"
"                        const myObject = JSON.parse(jsObject[curr]);\n"
"                        sentx2 = \"[\" + myObject.hash + \"] (\" + myObject.chan + \") \"\n"
"                        if(myObject.reply)\n"
"                            {\n"
"                            if(myObject.isok)\n"
"                                sentx2 += \"<font color=blue>\" + myObject.reply +\n"
"                                        \"</font>\";\n"
"                            else\n"
"                                sentx2 += \"<font color=red>\" + myObject.reply +\n"
"                                         \"</font>\";\n"
"                            const rssiInput = document.getElementById('rssi');\n"
"                            rssiInput.innerHTML =   \"Last RSSI: \" + jsObject.rssi;\n"
"                            const ppmInput = document.getElementById('ppm');\n"
"                            ppmInput.innerHTML = \" &nbsp; PPM: \" + jsObject.ppm.toFixed(2);\n"
"                            const deviInput = document.getElementById('devi');\n"
"                            deviInput.innerHTML = \" &nbsp; devi: \" + jsObject.devi.toFixed(2);\n"
"                            //rssiInput.innerHTML += \" &nbsp; Last Ack: \" + jsObject.ack;\n"
"                            //rssiInput.innerHTML += \" &nbsp; Devi: \" + jsObject.devi;\n"
"                            }\n"
"                        else\n"
"                            {\n"
"                            sentx2 += myObject.text\n"
"                            }\n"
"                        sentx += sentx2 + \"<br>\";\n"
"                        }\n"
"                    else\n"
"                        {\n"
"                        //break;\n"
"                        }\n"
"                    }\n"
"                //console.log(\"update %d '%d' \", xhr.status, jsObject.update);\n"
"                //console.log(\"sentx:\", sentx);\n"
"                const histInput = document.getElementById('hist');\n"
"                histInput.innerHTML = sentx;\n"
"                histInput.scrollTop = histInput.scrollHeight;\n"
"                }\n"
"            // Update the live data every xx msec\n"
"            redo_timer();\n"
"            }\n"
"    }\n"
"});\n"
"function redo_timer()\n"
"{\n"
"    // prevent duplicate timer\n"
"    if (timeoutID)\n"
"        {\n"
"        clearTimeout(timeoutID);\n"
"        }\n"
"    timeoutID = setTimeout(updateLiveData, 1000);\n"
"}\n"
"</script>\n"
"<style>\n"
".container {\n"
"  display: flex; /* Makes the container a flex container */\n"
"  //width: 100%;\n"
"  border-width: 0px;\n"
"}\n"
".resdiv {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    display: inline-block;\n"
"    vertical-align: top;\n"
"    horizontal-align: right;\n"
"    flex-grow: 1;\n"
"    overflow: auto;\n"
"    height: 200px;\n"
"}\n"
"</style>\n"
"<script async>\n"
"    //console.log(\"Start program\");\n"
"    //alert(\"start\");\n"
"    window.addEventListener('load', function() {\n"
"        //console.log(\"Start load\");\n"
"        const checkInput = document.getElementById('prom');\n"
"        if (checkInput) {\n"
"            checkInput.addEventListener('change', checkprom , false);\n"
"        }\n"
"    document.querySelector('form').addEventListener('submit', (event) => {\n"
"        event.preventDefault();\n"
"        // Handle data manually here\n"
"        });\n"
"    });\n"
"    const isNumeric = (str) => Number.isFinite(+str);\n"
"    const truncateString = (str, num) => {\n"
"          if (str.length > num) {\n"
"            return str.slice(0, num) + \"...\";\n"
"          } else {\n"
"            return str;\n"
"          }\n"
"        };\n"
"    var escapeHTML = function(unsafe) {\n"
"      return unsafe.replace(/[&<>\"']/g, function(m) {\n"
"        switch (m) {\n"
"          case '&':\n"
"            return '&amp;';\n"
"          case '<':\n"
"            return '&lt;';\n"
"          case '>':\n"
"            return '&gt;';\n"
"          case '\"':\n"
"            return '&quot;';\n"
"          default:\n"
"            return '&#039;';\n"
"        }\n"
"      });\n"
"    };\n"
"    // Re - write in javascript\n"
"    function chksum(strx) {\n"
"        //console.log(\"chksum() strx='%s'\", strx);\n"
"        let ret = 0;\n"
"        for(aa = 0; aa < strx.length; aa++)\n"
"            {\n"
"            nn = strx.charCodeAt(aa);\n"
"            //console.log(nn);\n"
"            qq = nn << 7 | nn;\n"
"            qq = qq & 0xffff;\n"
"            ret += qq + 10000;\n"
"            ret = ret & 0xffff;\n"
"            ret ^= 0x5aa5;\n"
"            ret = ret & 0xffff;\n"
"            }\n"
"        //console.log(\"sum ret=%s\", ret.toString(16));\n"
"        return(ret);\n"
"    }\n"
"    // Pressed checkbox\n"
"    async function checkprom() {\n"
"        const checkInput = document.getElementById('prom');\n"
"        const chanInput = document.getElementById('chan');\n"
"        //console.log(\"Check pressed\", checkInput.checked)\n"
"        if (!chanInput.value)\n"
"            return;\n"
"        jsonString = '{\"check\": ' + checkInput.checked + ', \"chan\": \"'\n"
"                        + chanInput.value +  '\" }';\n"
"        redo_timer();\n"
"        const response = await fetch(\"post.html\", {\n"
"                method: 'POST',\n"
"                headers: { 'Content-Type': 'application/json' },\n"
"                body: jsonString\n"
"                })\n"
"    }\n"
"    function check_number(valx, lower, upper) {\n"
"        if (valx < lower || valx > upper)\n"
"            {\n"
"            alert(\"Trench number out of range.\");\n"
"            return 0;\n"
"            }\n"
"        return 1;\n"
"        }\n"
"    async function pressed_sub() {\n"
"        // Check parameters\n"
"        const textInput = document.getElementById('txt');\n"
"        const chanInput = document.getElementById('chan');\n"
"        if (chanInput.value == \"\")\n"
"            chanInput.value = 0;       // Auto zero\n"
"        if (!isNumeric(chanInput.value))\n"
"            {\n"
"            alert(\"Cannot submit a non number for trench \");\n"
"            textInput.focus();\n"
"            return;\n"
"            }\n"
"        if (!check_number(chanInput.value, 0, 0xffff))\n"
"            {\n"
"            return;\n"
"            }\n"
"        if (textInput.value == \"\")\n"
"            {\n"
"            //console.log(\"Empty string. Not Submitting\");\n"
"            alert(\"Cannot submit empty message.\");\n"
"            textInput.focus();\n"
"            return;\n"
"            }\n"
"        textInput.value = escapeHTML(textInput.value);\n"
"        const formData = new FormData(myform);\n"
"        const plainFormData = Object.fromEntries(formData.entries());\n"
"        if(plainFormData['text'].length > 230)\n"
"            {\n"
"            alert(\"Truncating message to 230 bytes\");\n"
"            plainFormData['text'] = truncateString(plainFormData['text'], 230);\n"
"            }\n"
"        textInput.disabled = true\n"
"        const num = chksum(plainFormData['text']);\n"
"        plainFormData['hash'] = num.toString(16);\n"
"        //plainFormData['answer'] = \"Awaiting ...\";\n"
"        const jsonString = JSON.stringify(plainFormData);\n"
"        //console.log(\"Submitting '%s'\", jsonString);\n"
"        const response = await fetch(\"post.html\", {\n"
"                method: 'POST',\n"
"                headers: { 'Content-Type': 'application/json' },\n"
"                body: jsonString\n"
"                })\n"
"        const data = await response.text();\n"
"        //console.log(\"Data from await: '%s'\", data);\n"
"        // Fill in current state\n"
"        const textOutput = document.getElementById('current');\n"
"        textOutput.innerHTML = data;\n"
"        setTimeout(updateLiveData, 1000);\n"
"    }\n"
"function textUpdate() {\n"
"    const textInput = document.getElementById('txt');\n"
"    //console.log('Text area content changed in real-time.' +\n"
"    //                 textInput.value.length);\n"
"    const cntOutput = document.getElementById('cnt');\n"
"    cntOutput.innerHTML = \"Count: \" + textInput.value.length;\n"
"}\n"
"function chanUpdate() {\n"
"    checkprom();\n"
"}\n"
"window.addEventListener('load', () => {\n"
"    const textInput = document.getElementById('txt');\n"
"    textInput.addEventListener('input', textUpdate)\n"
"    const chanInput = document.getElementById('chan');\n"
"    chanInput.addEventListener('input', chanUpdate)\n"
"    const cntOutput = document.getElementById('cnt');\n"
"    cntOutput.innerHTML = \"Count: \" + textInput.value.length;\n"
"});\n"
"window.addEventListener(\"keydown\", onKeyDown, true);\n"
"window.addEventListener(\"keyup\", onKeyUp, true);\n"
"ctrl = 0;\n"
"function onKeyDown(e){\n"
"    //console.log(\"Dn \" + e.key);\n"
"    if(e.key == \"Enter\" && ctrl == 1)\n"
"        {\n"
"        const textInput = document.getElementById('txt');\n"
"        //console.log(\"Ctrl-Enter: '%s'\", textInput.value )\n"
"        //e.preventDefault();\n"
"        pressed_sub();\n"
"        }\n"
"    if(e.key == \"Control\")\n"
"        {\n"
"        ctrl = 1\n"
"        }\n"
"    else\n"
"        {\n"
"        ctrl = 0\n"
"        }\n"
"  }\n"
"function onKeyUp(e){\n"
"    //console.log(\"Up \" + e.key);\n"
"    if(e.key == \"Control\")\n"
"        {\n"
"        ctrl = 0\n"
"        }\n"
"  }\n"
"</script>\n"
"<table align=center width=100% padding=1>\n"
"    <tr><td> Data: <td colspan=3>\n"
"        <div class=\"container\">\n"
"            <div class=resdiv id=hist> Nothing received yet ... &nbsp; </div>\n"
"        </div>\n"
"    <tr><td>\n"
"        Trench:\n"
"        <td><input type=text name=chan id=chan value=trenchtrenchtrench> (0-65534)\n"
"        <td>\n"
"        <input type=checkbox name=prom id=prom>\n"
"        <label for=\"prom\">Show all trenches</label>\n"
"        <td> &nbsp;\n"
"    <tr><td>\n"
"        Send:\n"
"        <td colspan=2>\n"
"        <textarea autofocus name=text rows=4 cols=64 id=txt></textarea>\n"
"        <td align=center>\n"
"                          <div id=cnt>Count: 0</div>\n"
"                          <i>Max 230 Characters</i><br>\n"
"                          Ctrl-Enter to submit <p>\n"
"            <input type=button value=Send onclick=pressed_sub()><br>\n"
"            <div id=status></div>\n"
"    <tr><td>\n"
"        Status:\n"
"        <td class=mydiv>\n"
"            <div class=mytext id=current>Idle.</div>\n"
"        <td class=mydiv colspan=2>\n"
"            <table width=100%>\n"
"                <td class=mydiv>\n"
"                    <div class=mytext id=rssi> Last RSSI: 0\n"
"                    </div>\n"
"                <td class=mydiv>\n"
"                    <div class=mytext id=devi> Last devi: 0\n"
"                    </div>\n"
"                <td class=mydiv>\n"
"                    <div class=mytext id=ppm> Last PPM: 0\n"
"                    </div>\n"
"            </table>\n"
"</table>\n"
"<tr><td>\n"
"  <table width=100% border=0>\n"
"        <tr>\n"
"            <td align=center colspan=3 width=100%>\n"
"            <hr>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_4.html> Main Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_2.html> WiFi Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                 <div style=\"font-size:large\"   align=center>\n"
"                    <a href=page_3.html> LORA Parameters </a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                    <a href=page_8.html> Quick Start Manual </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html> Go to Home Page </a>\n"
"                </div>\n"
"           <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html?reboot=true>Reboot Device</a>\n"
"                </div>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <font color=#0000ff>\n"
"            comstatcomstatcomstatcomstatcomstat\n"
"            </font>\n"
"        </div>\n"
"    </table>\n"
"    <tr>\n"
"    <td colspan=2 align=center>\n"
"    <hr>\n"
"    <!--<tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <a href=page_1.html?home=true>Back to Home Page</a>\n"
"        </div>\n"
"    -->\n"
"    <tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:small\">\n"
"            ID (Main) (Mac Address): macmacmacmacmacmacmac<br>\n"
"            Current Boot Count:  bcountbcount<br>\n"
"            Software Version / Build Date: softversoftversoftversoftversoftversoftver<br>\n"
"        </div>\n"
"    <tr><td colspan=2 align=center>\n"
"        Peter Glen, (C) 2026 <br>\n"
"    <tr><td colspan=2 align=center>\n"
"</table>\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
// EOF
