
/* =====[ ESP32 project ]=================================================

   File Name:       main/html/page_x.html

   Description:     Main file

   Revisions:       (for the original file)

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  Tue, 24-03-26   Peter Glen      Initial version.

   ======================================================================= */

// Page contents as header. DO NOT EDIT. Contents are overwritten at
// compile time.
// Edit the corresponding HTML file instead: main/html/page_x.html

const char notfound_html [] =

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n"
"<html>\n"
"<head>\n"
"<title>LORAWIFI Missing Page</title>\n"
"<meta charset=\"UTF-8\">\n"
"<link rel='icon' href='data:;base64,iVBORw0KGgo='>\n"
"</head>\n"
"<body>\n"
"<form method=post id=myform>\n"
"<table align=center border=0 width=800 frame=void>\n"
"<style>\n"
".container {\n"
"	text-align: left;\n"
"	border: 1px solid green;\n"
"	padding: 5px;\n"
"    }\n"
".container table {\n"
"	border: 1px solid red;\n"
"    margin: 0 auto;\n"
"    }\n"
".chris {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2a  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2b  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2c  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris3  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      16px;\n"
"    }\n"
".myDiv {\n"
"  font-size: 100px;\n"
"  text-align: center;\n"
"}\n"
"html, address, blockquote, body, dd, div, dl, dt, fieldset,\n"
"form, h1, h2, h3, h4, h5, h6, noframes, ol, p, ul, center,\n"
"dir, hr, menu, pre {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    }\n"
".mydiv {\n"
"    /*background:yellow;\n"
"    color:blue;\n"
"    border-style:solid;\n"
"    border-width:medium;\n"
"    display:inline-block;\n"
"    */\n"
"    vertical-align:top;\n"
"    horizontal-align:right;\n"
"}\n"
"textarea {\n"
"    border-color:#eeeeee;\n"
"    width:90%;\n"
"}\n"
".mytext {\n"
"    /*background:yellow;\n"
"    color:blue;*/\n"
"    width:100%;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:#eeeeee;\n"
"    display:inline-block;\n"
"}\n"
".rebootstat {\n"
"    font-size:  16px;\n"
"    color:      red;\n"
"}\n"
".statstat {\n"
"    font-size:  16px;\n"
"    color:      blue;\n"
"}\n"
"    </style>\n"
"</style>\n"
"<tr><td>\n"
"    <table width=100% border=0>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"    <a href=page_1.html?home=true style=\"text-decoration: none; color: black;\">\n"
"        <div class=\"chris\" align=center>\n"
"            LORA WiFi Transceiver\n"
"        </div>\n"
"    </a>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div id=status class=statstat align=center>\n"
"            StatusStatusStatusStatusStatusStatusStatusStatus\n"
"        </div>\n"
"    </table>\n"
"<center>\n"
"<hr>\n"
"<font size=6>The requested Page is Not Found</font>\n"
"</center>\n"
"<tr><td>\n"
"  <table width=100% border=0>\n"
"        <tr>\n"
"            <td align=center colspan=3 width=100%>\n"
"            <hr>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_4.html> Main Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_2.html> WiFi Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                 <div style=\"font-size:large\"   align=center>\n"
"                    <a href=page_3.html> LORA Parameters </a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                    <a href=page_8.html> Quick Start Manual </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html> Back to Home Page </a>\n"
"                </div>\n"
"           <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html?reboot=true>Reboot Device</a>\n"
"                </div>\n"
"    </table>\n"
"    <tr>\n"
"    <td colspan=2 align=center>\n"
"    <hr>\n"
"    <!--<tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <a href=page_1.html?home=true>Back to Home Page</a>\n"
"        </div>\n"
"    -->\n"
"    <tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:small\">\n"
"            ID (Main) (Mac Address): macmacmacmacmacmacmac<br>\n"
"            Current Boot Count:  bcountbcount<br>\n"
"            Software Version / Build Date: softversoftversoftversoftversoftversoftver<br>\n"
"        </div>\n"
"    <tr><td colspan=2 align=center>\n"
"        Peter Glen, (C) 2026 <br>\n"
"    <tr><td colspan=2 align=center>\n"
"</table>\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
// EOF
