
/* =====[ ESP32 project ]=================================================

   File Name:       main/html/page_8.html

   Description:     Main file

   Revisions:       (for the original file)

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  Sun, 15-03-26   Peter Glen      Initial version.

   ======================================================================= */

// Page contents as header. DO NOT EDIT. Contents are overwritten at
// compile time.
// Edit the corresponding HTML file instead: main/html/page_8.html

const char manual_html [] =

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n"
"<html>\n"
"<head>\n"
"<title>LORA WiFi User Manual</title>\n"
"<meta charset=\"UTF-8\">\n"
"<link rel='icon' href='data:;base64,iVBORw0KGgo='>\n"
"</head>\n"
"<body>\n"
"<form method=post id=myform>\n"
"<table align=center border=0 width=800 frame=void>\n"
"<style>\n"
".container {\n"
"	text-align: left;\n"
"	border: 1px solid green;\n"
"	padding: 5px;\n"
"    }\n"
".container table {\n"
"	border: 1px solid red;\n"
"    margin: 0 auto;\n"
"    }\n"
".chris {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2a  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2b  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2c  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris3  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      16px;\n"
"    }\n"
".myDiv {\n"
"  font-size: 100px;\n"
"  text-align: center;\n"
"}\n"
"html, address, blockquote, body, dd, div, dl, dt, fieldset,\n"
"form, h1, h2, h3, h4, h5, h6, noframes, ol, p, ul, center,\n"
"dir, hr, menu, pre {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    }\n"
".mydiv {\n"
"    /*background:yellow;\n"
"    color:blue;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    display:inline-block;\n"
"    */\n"
"    vertical-align:top;\n"
"    horizontal-align:right;\n"
"}\n"
"textarea {\n"
"    border-color:#eeeeee;\n"
"    width:90%;\n"
"}\n"
".mytext {\n"
"    /*background:yellow;\n"
"    color:blue;*/\n"
"    width:100%;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:#eeeeee;\n"
"    display:inline-block;\n"
"}\n"
"</style>\n"
"<tr><td>\n"
"    <table width=100% border=0>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"    <a href=page_1.html?home=true style=\"text-decoration: none; color: black;\">\n"
"        <div class=\"chris\" align=center>\n"
"            LORA WiFi Transceiver\n"
"        </div>\n"
"    </a>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <font color=#0000ff>\n"
"            StatusStatusStatusStatusStatusStatusStatusStatus\n"
"            </font>\n"
"        </div>\n"
"    </table>\n"
"<table width=100%>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi transceiver (transmitter / receiver) is a long range\n"
"    pier to pier communcation device.\n"
"    In the paragraphs below, a quick description of the\n"
"    device's configuration and operation is detailed.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Communcation</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi is ready to communicate out of the box; Just plug\n"
"    it in to any USB, and connect to its web page. One may connect with any\n"
"    standard browser, a phone, tablet, computer, or any other browser capable\n"
"    device. Once connected, use the provided text box to send a message.\n"
"    The message should show up on the other device, configured to the same channel.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Quick Setup, Channel configuration</b>\n"
"        </div>\n"
"    <tr><td   style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi system comes set to channel zero from the manufacturer.\n"
"    Should a different channel be needed, the process extremely simple: just\n"
"    enter a new channel number in the channel configuration box. The channel number\n"
"    can be from 0 to 65535. Both the receiver and transmitter has to be on the same channel.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Channel Safety</b>\n"
"        </div>\n"
"    <tr><td   style=\"text-align:justify;\">\n"
"        Because the device comes configured at channel 0, it is meant to be\n"
"        a test channel for initial communication test. It is recommended to\n"
"        change the channel after successfully testing communication.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Pairing Safety</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; Channel safety measures:\n"
"    <ul> <li>Both the receiver and transmitter has to be on the same channel.\n"
"    <li>Both the receiver and transmitter has to have\n"
"    tha same LORA parmeters. </ul>\n"
"    &nbsp; &nbsp; If one encounters any difficulty during the pairing process, a long press reset on the\n"
"    receiver will clear all pairing data, and allows a fresh start. Note that after long press reset, all\n"
"    the other devices that where paired to this receiver need to be re-paired.\n"
"    <tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Quick Setup, Enable Configuration</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi system starts up in transmit / receive mode on channel 0.\n"
"    One may connect to the device's web page to use it and to configure it.\n"
"    If no communication activity occurs in one minute, the device will\n"
"    terminate the configuration mode, and resume in communication mode.\n"
"<tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Features, Encryption and Checksum:</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi system communicates with an unencrypted data stream.\n"
"    However, the data is protected with a checksum. Data cannot be falsified\n"
"    by external sources, as the LORA WiFi will reject packets with an invalid\n"
"    checksum. If one desires extra secrecy, there are plenty of applications\n"
"    that serve this purpose on the browser / text entry level. However, tweaking\n"
"    the LORA parameters may serve as a good substitute, as guessing the correct\n"
"    LORA parameters can be as challenging as breaking encryption.\n"
"<tr><td>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"        <b>Distance expectations:</b>\n"
"        </div>\n"
"    <tr><td  style=\"text-align:justify;\">\n"
"    &nbsp; &nbsp; The LORA WiFi system utilizes a SEMTEC LORA device. The LORA\n"
"     device's specification suggest an 8 kilometer line of sight range.\n"
"     Under ideal conditions, this can be measured and proven with this\n"
"     implementation, and it delivers according to specification. Using\n"
"     the device in a non line of sight configuration the range is\n"
"     significantly less. For instance using in highrise building area, the\n"
"     range can be as little as 500 meters.\n"
"    <br>\n"
"</table>\n"
"<tr><td>\n"
"  <table width=100% border=0>\n"
"        <tr>\n"
"            <td align=center colspan=2 width=100%>\n"
"            <hr>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_2.html>WiFi Settings</a>\n"
"                </div>\n"
"            <td align=center>\n"
"                 <div style=\"font-size:large\"   align=center>\n"
"                    <a href=page_3.html> LORA Parameters</a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                    <a href=page_8.html> Quick Start Manual</a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html?reboot=true>Reboot Device</a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center colspan=2>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html>Back to Home Page</a>\n"
"                </div>\n"
"    </table>\n"
"    <tr>\n"
"    <td colspan=2 align=center>\n"
"    <hr>\n"
"    <!--<tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <a href=page_1.html?home=true>Back to Home Page</a>\n"
"        </div>\n"
"    -->\n"
"    <tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:small\">\n"
"            ID (Main) (Mac Address): macmacmacmacmacmacmac<br>\n"
"            Current Boot Count:  bcountbcount<br>\n"
"            Software Version / Build Date: softversoftversoftversoftversoftversoftver<br>\n"
"        </div>\n"
"    <tr><td colspan=2 align=center>\n"
"        Peter Glen, (C) 2026 <br>\n"
"    <tr><td colspan=2 align=center>\n"
"</table>\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
// EOF
