
/* =====[ ESP32 project ]=================================================

   File Name:       main/html/page_2.html

   Description:     Main file

   Revisions:       (for the original file)

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  Sat, 21-03-26   Peter Glen      Initial version.

   ======================================================================= */

// Page contents as header. DO NOT EDIT. Contents are overwritten at
// compile time.
// Edit the corresponding HTML file instead: main/html/page_2.html

const char settings_html [] =

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n"
"<html>\n"
"<head>\n"
"<title>LORA WiFi Network Settings</title>\n"
"<meta charset=\"UTF-8\">\n"
"<link rel='icon' href='data:;base64,iVBORw0KGgo='>\n"
"</head>\n"
"<body>\n"
"<form method=post id=myform>\n"
"<table align=center border=0 width=800 frame=void>\n"
"<script async>\n"
"// Use this to set witout raising error\n"
"function assign_text(ctrl, valx)\n"
"{\n"
"    ddd = document.getElementById(ctrl)\n"
"    if(ddd)\n"
"        {\n"
"        ddd.innerHTML = valx\n"
"        }\n"
"    else\n"
"        {\n"
"        //console.log(\"assign_text -- NO such control\", ctrl);\n"
"        }\n"
"    // See if there is a progress bar\n"
"}\n"
"function assign_color(ctrl, valx)\n"
"{\n"
"    ddd = document.getElementById(ctrl)\n"
"    if(ddd)\n"
"        {\n"
"        ddd.style.backgroundColor = valx;\n"
"        }\n"
"    else\n"
"        {\n"
"        //console.log(\"assign_color -- NO such control\", ctrl);\n"
"        }\n"
"}\n"
"function walk_templine(xstr, num)\n"
"{\n"
"    //console.log(\"walk_templine %d '%s' \", num, xstr);\n"
"    var prog = 0;\n"
"    var idx = xstr.indexOf(\" \");\n"
"    if(idx >= 0)\n"
"        {\n"
"        var  sss = Number(xstr.slice(prog, idx))\n"
"        //console.log(\"sss '%s' \", sss);\n"
"        var  ccc = xstr.slice(idx+1, xstr.length)\n"
"        //console.log(\"ccc '%s' \", ccc);\n"
"        var  idx2 = ccc.indexOf(\" \")\n"
"        if(idx2 >= 0)\n"
"            {\n"
"            var  ddd = Number(ccc.slice(0, idx2))\n"
"            //console.log(\"ddd '%s' \", ddd);\n"
"            if(ddd == -100)\n"
"                assign_text('tab_' + (num + 1), \"SENSOR?\" )\n"
"            else\n"
"                assign_text('tab_' + (num + 1), ddd.toFixed(2) + \" &#8451\")\n"
"            }\n"
"        }\n"
"}\n"
"function walk_a2dline(xstr, num)\n"
"{\n"
"    //console.log(\"walk_a2dline %d '%s' \", num, xstr);\n"
"    var prog = 0;\n"
"    var idx = xstr.indexOf(\" \");\n"
"    if(idx >= 0)\n"
"        {\n"
"        var  sss = xstr.slice(prog, idx)\n"
"        //console.log(\"sss '%s' \", sss);\n"
"        //assign_text( (num + 1) + 'h', sss )             // Set current data text\n"
"        var  ccc = xstr.slice(idx+1, xstr.length)\n"
"        //console.log(\"ccc '%s' \", ccc);\n"
"        var  idx2 = ccc.indexOf(\" \")\n"
"        if(idx2 >= 0)\n"
"            {\n"
"            var  dddd = Number(ccc.slice(0, idx2) )\n"
"            //console.log(\"dddd '%s' \", dddd);\n"
"            if((dddd < 0.) || (dddd > 15.))\n"
"                {\n"
"                assign_text((num + 1) + 'h', \"OOR\");\n"
"                assign_text((num + 1) + 'i', \"OOR\");\n"
"                //assign_text((num + 1) + 'j', \"OOR\");\n"
"                }\n"
"            else\n"
"                {\n"
"                //assign_text((num + 1) + 'h', (dddd / 4096 * 5).toFixed(2) +    \" V\")\n"
"                //assign_text((num + 1) + 'i', (dddd / 4096 * 10).toFixed(2) +   \" V\")\n"
"                assign_text((num + 1) + 'i', dddd.toFixed(2) +   \" V\")\n"
"                assign_text((num + 1) + 'j', (dddd / 10 * 100).toFixed(2) + \" %\")\n"
"                }\n"
"            }\n"
"        }\n"
"}\n"
"function walk_swline(xstr, num)\n"
"{\n"
"    //console.log(\"walk_swline %d '%s' \", num, xstr);\n"
"    var prog = 0;\n"
"    var idx = xstr.indexOf(\" \");\n"
"    if(idx >= 0)\n"
"        {\n"
"        var  sss = xstr.slice(prog, idx)\n"
"        //console.log(\"sss %d '%s' \", num, sss);\n"
"        assign_text( (num + 1) + 'c', sss )             // Set current data text\n"
"        var  ccc = xstr.slice(idx+1, xstr.length)\n"
"        //console.log(\"ccc %d '%s' \", num, ccc);\n"
"        var  idx2 = ccc.indexOf(\" \")\n"
"        if(idx2 >= 0)\n"
"            {\n"
"            var  dddd = ccc.slice(0, idx2)\n"
"            //console.log(\"dddd %n '%s' \", num, dddd);\n"
"            assign_text((num + 1) + 'd', dddd )\n"
"            }\n"
"        }\n"
"}\n"
"function walk_relline(xstr, num)\n"
"{\n"
"    //console.log(\"walk_relline %d '%s' \", num, xstr);\n"
"    var prog = 0;\n"
"    var idx = xstr.indexOf(\" \");\n"
"    if(idx >= 0)\n"
"        {\n"
"        var  sss = xstr.slice(prog, idx)\n"
"        //console.log(\"sss '%s' \", sss);\n"
"        //assign_text(\"rel_\" +  (num + 1), sss )             // Set current data text\n"
"        var  ccc = xstr.slice(idx+1, xstr.length)\n"
"        //console.log(\"ccc '%s' \", ccc);\n"
"        var  idx2 = ccc.indexOf(\" \")\n"
"        if(idx2 >= 0)\n"
"            {\n"
"            var  dddd = Number(ccc.slice(0, idx2))\n"
"            var nnn = \"rel_\" + (num + 1)\n"
"            //console.log(\" nnn \" + nnn + \" dddd \" + dddd );\n"
"            if (dddd == 0)\n"
"                {\n"
"                assign_text(nnn, \"OFF\" )\n"
"                assign_color(nnn, \"#bbbbbb\")\n"
"                }\n"
"            else\n"
"                {\n"
"                assign_text(nnn, \"ON \" )\n"
"                assign_color(nnn, \"#ffaa00\")\n"
"                }\n"
"            }\n"
"        }\n"
"}\n"
"function walk_nums(xstr)\n"
"{\n"
"    //console.log(\"walk_nums '%s' \", xstr);\n"
"    var prog = 0;\n"
"    var num = 0;\n"
"    while(1)\n"
"        {\n"
"        var idx = xstr.indexOf(\"\\n\", prog);\n"
"        if(idx < 0)\n"
"            break;\n"
"        if(num < 8)\n"
"            {\n"
"            walk_swline(xstr.slice(prog, idx), num)\n"
"            }\n"
"        else if(num < 12)\n"
"            {\n"
"            walk_a2dline(xstr.slice(prog, idx), num-8)\n"
"            }\n"
"        else if(num < 14)\n"
"            {\n"
"            walk_templine(xstr.slice(prog, idx), num-12)\n"
"            }\n"
"        else\n"
"            {\n"
"            walk_relline(xstr.slice(prog, idx), num-14)\n"
"            }\n"
"        prog = idx+1\n"
"        num = num + 1\n"
"        }\n"
"}\n"
"//window.addEventListener('load', function()\n"
"//{\n"
"//    //startTime();\n"
"//\n"
"//    var xhr = null;\n"
"//    var xhr2 = null;\n"
"//\n"
"//    getXmlHttpRequestObject = function()\n"
"//    {\n"
"//        if(!xhr)\n"
"//        {\n"
"//            // Create a new XMLHttpRequest object\n"
"//            xhr = new XMLHttpRequest();\n"
"//        }\n"
"//        return xhr;\n"
"//    };\n"
"//    //getXmlHttpRequestObject2 = function()\n"
"//    //{\n"
"//    //    if(!xhr2)\n"
"//    //    {\n"
"//    //        // Create a new XMLHttpRequest object\n"
"//    //        xhr2 = new XMLHttpRequest();\n"
"//    //    }\n"
"//    //    return xhr2;\n"
"//    //};\n"
"//\n"
"//    updateLiveData = function()\n"
"//    {\n"
"//        var url = 'swtable.txt?'\n"
"//        // + now.getTime();\n"
"//        xhr = getXmlHttpRequestObject();\n"
"//        xhr.onreadystatechange = evenHandler;\n"
"//        // asynchronous requests\n"
"//        xhr.open(\"GET\", url, true);\n"
"//        // Send the request over the network\n"
"//        xhr.send(null);\n"
"//    };\n"
"//    //updateLiveData2 = function()\n"
"//    //{\n"
"//    //    var url2 = 'swtable2.txt?'\n"
"//    //    // + now.getTime();\n"
"//    //    xhr2 = getXmlHttpRequestObject2();\n"
"//    //    xhr2.onreadystatechange = evenHandler2;\n"
"//    //    // asynchronous requests\n"
"//    //    xhr2.open(\"GET\", url2, true);\n"
"//    //    // Send the request over the network\n"
"//    //    xhr2.send(null);\n"
"//    //};\n"
"//    updateLiveData();\n"
"//    //updateLiveData2();\n"
"//\n"
"//    function evenHandler()\n"
"//    {\n"
"//        //console.log(\"Answer %d %d '%s' \",\n"
"//        //        xhr.readyState, xhr.status, xhr.responseText);\n"
"//\n"
"//        // Check response is ready or not\n"
"//        if(xhr.readyState == 4 && xhr.status == 200)\n"
"//            {\n"
"//            // Walk all the numbers\n"
"//            walk_nums(xhr.responseText)\n"
"//            // Update the live data every xx msec\n"
"//            setTimeout(updateLiveData, 200);\n"
"//            }\n"
"//    }\n"
"//    function evenHandler2()\n"
"//    {\n"
"//        // Check response is ready or not\n"
"//        if(xhr2.readyState == 4 && xhr2.status == 200)\n"
"//        {\n"
"//            //dataDiv = document.getElementById('liveTable');\n"
"//            // Set current data text\n"
"//            //dataDiv.innerHTML = xhr2.responseText;\n"
"//            // Update the live data every 1 sec\n"
"//            //setTimeout(updateLiveData2(), 600);\n"
"//        }\n"
"//    }\n"
"//});\n"
"function padTime(i) {\n"
"  if (i < 10) {i = \"0\" + i};\n"
"  return i;\n"
"}\n"
"var     cnt = 0;\n"
"function updTime() {\n"
"    var today = new(Date);    var today3 = new(Date);\n"
"    today3.setTime(today.getTime() +\n"
"                    today_remote.getTime() - today_org.getTime());\n"
"    var hh = today3.getHours();\n"
"    var mm = today3.getMinutes();\n"
"    var ss = today3.getSeconds();\n"
"    var amstr = \"\";\n"
"    if(ampm) {\n"
"        if (hh >= 12) { amstr = \"PM\"; }\n"
"        else   { amstr = \"AM\"; }\n"
"        if(hh > 12) { hh -= 12; }\n"
"        }\n"
"    hh = padTime(hh);  mm = padTime(mm);  ss = padTime(ss);\n"
"    //document.getElementById('ddd').innerHTML = amstr;\n"
"    ttt = hh + \":\" + mm + \":\" + ss + \" \";\n"
"    cnt += 103\n"
"    //document.getElementById('1c').innerHTML = cnt +1\n"
"    //document.getElementById('1d').innerHTML = cnt +2\n"
"    document.getElementById('2c').innerHTML = cnt +3\n"
"    document.getElementById('2d').innerHTML = cnt +4\n"
"    document.getElementById('3c').innerHTML = cnt +5\n"
"    document.getElementById('3d').innerHTML = cnt +6\n"
"    document.getElementById('4c').innerHTML = cnt +7\n"
"    document.getElementById('4d').innerHTML = cnt +8\n"
"    document.getElementById('5c').innerHTML = cnt +1\n"
"    document.getElementById('5d').innerHTML = cnt +2\n"
"    document.getElementById('6c').innerHTML = cnt +3\n"
"    document.getElementById('6d').innerHTML = cnt +4\n"
"    document.getElementById('7c').innerHTML = cnt +5\n"
"    document.getElementById('7d').innerHTML = cnt +6\n"
"    document.getElementById('8c').innerHTML = cnt +7\n"
"    document.getElementById('8d').innerHTML = cnt +8\n"
"    var t = setTimeout(updTime, 500);\n"
"}\n"
"function startTime() {\n"
"  //today_org  = new Date();  today_remote = new Date();\n"
" // var doc = document.getElementById('ccc');  var sstr = doc.innerHTML\n"
"//  var ddoc = document.getElementById('ddd'); var dstr = ddoc.innerHTML\n"
"//\n"
"//  /* console.log(\"got_time_0 '%s' \", sstr);*/\n"
"//  /*console.log(\"got_ampm_0 '%s' \", dstr);*/\n"
"//  var  hhh = sstr.slice(1, 3);  var  mmm =  sstr.slice(4, 6);\n"
"//  var  sss = sstr.slice(7, 9)\n"
"//  var hhhh = Number(hhh); var ssss = Number(sss);\n"
"//  var mmmm = Number(mmm);\n"
"//  if(dstr.indexOf(\"AM\") >= 0) {\n"
"//    ampm = true;\n"
"//    }\n"
"//  else if(dstr.indexOf(\"PM\") >= 0)  {\n"
"//    ampm = true;\n"
"//    hhhh += 12;\n"
"//    }\n"
"//  else {\n"
"//    /*console.log(\"got_none\");*/\n"
"//    }\n"
"//\n"
"//  today_remote.setHours(hhhh);\n"
"//  today_remote.setMinutes(mmmm);\n"
"//  today_remote.setSeconds(ssss);\n"
"//  /*console.log(\"hhh='%s' mmm='%s' sss='%s' ampm='%s'\", hhh, mmm, sss, ampm);*/\n"
"//  /*console.log(\"remote: %d org: %d\",  today_remote, today_org);*/\n"
"    //var t = setTimeout(updTime, 500);\n"
"}\n"
"</script>\n"
"<style>\n"
".container {\n"
"	text-align: left;\n"
"	border: 1px solid green;\n"
"	padding: 5px;\n"
"    }\n"
".container table {\n"
"	border: 1px solid red;\n"
"    margin: 0 auto;\n"
"    }\n"
".chris {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2a  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2b  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2c  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris3  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      16px;\n"
"    }\n"
".myDiv {\n"
"  font-size: 100px;\n"
"  text-align: center;\n"
"}\n"
"html, address, blockquote, body, dd, div, dl, dt, fieldset,\n"
"form, h1, h2, h3, h4, h5, h6, noframes, ol, p, ul, center,\n"
"dir, hr, menu, pre {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    }\n"
".mydiv {\n"
"    /*background:yellow;\n"
"    color:blue;\n"
"    border-style:solid;\n"
"    border-width:medium;\n"
"    display:inline-block;\n"
"    */\n"
"    vertical-align:top;\n"
"    horizontal-align:right;\n"
"}\n"
"textarea {\n"
"    border-color:#eeeeee;\n"
"    width:90%;\n"
"}\n"
".mytext {\n"
"    /*background:yellow;\n"
"    color:blue;*/\n"
"    width:100%;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:#eeeeee;\n"
"    display:inline-block;\n"
"}\n"
".rebootstat {\n"
"    font-size:  16px;\n"
"    color:      red;\n"
"}\n"
".statstat {\n"
"    font-size:  16px;\n"
"    color:      blue;\n"
"}\n"
"    </style>\n"
"</style>\n"
"<tr><td>\n"
"    <table width=100% border=0>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"    <a href=page_1.html?home=true style=\"text-decoration: none; color: black;\">\n"
"        <div class=\"chris\" align=center>\n"
"            LORA WiFi Transceiver\n"
"        </div>\n"
"    </a>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div id=status class=statstat align=center>\n"
"            StatusStatusStatusStatusStatusStatusStatusStatus\n"
"        </div>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div id=reboot class=rebootstat>\n"
"            RebootRebootRebootRebootRebootRebootRebootRebootReboot\n"
"        </div>\n"
"    </table>\n"
"<script async>\n"
"    function containsPunctuation(strz) {\n"
"        // Regex to match a variety of common punctuation marks\n"
"        const punctuationRegex = /[!\"#$%&'()*,\\./:;<=>?@[\\^`{|}\\]~]/;\n"
"        return punctuationRegex.test(strz);\n"
"    }\n"
"    async function save_wifi() {\n"
"        //console.log(\"Save WIFI\");\n"
"        const formData = new FormData(myform);\n"
"        //console.log(\"formData\", formData);\n"
"        if(containsPunctuation(formData.get(\"apname\")))\n"
"            {\n"
"            alert(\"Wifi hostname cannot contain punctuation.\")\n"
"            return;\n"
"            }\n"
"        if(formData.get(\"appass\") != formData.get(\"appass2\"))\n"
"            {\n"
"            alert(\"Wifi passes must match.\")\n"
"            return;\n"
"            }\n"
"        if(formData.get(\"appass\").length < 8)\n"
"            {\n"
"            alert(\"Wifi pass must be 8 letters or longer.\")\n"
"            return;\n"
"            }\n"
"        const plainFormData = Object.fromEntries(formData.entries());\n"
"        const jsonString = JSON.stringify(plainFormData);\n"
"        //console.log(\"Submitting: '%s'\", jsonString);\n"
"        //document.getElementById(\"myform\").submit();\n"
"        const response = await fetch(\"page_2.html\", {\n"
"                method: 'POST',\n"
"                headers: { 'Content-Type': 'application/json' },\n"
"                body: jsonString\n"
"                })\n"
"        const data = await response.text();\n"
"        const confButt = document.getElementById('netbutt');\n"
"        //console.log(\"netbutt:\", confButt)\n"
"        confButt.value = data;\n"
"        const confReboot = document.getElementById('reboot');\n"
"        confReboot.innerHTML = \"Please reboot device for settings to take effect.\";\n"
"    }\n"
"</script>\n"
"<table width=100%>\n"
"    <tr><td colspan=2 align=center height=12>\n"
"    The following fields determine the Station Name and Password of this LORA WiFi.\n"
"    The device will appear on your WiFI network by this name. For safety and security,\n"
"    the LORA WiFi must be configured with a password. The password needs to be at\n"
"    least <font color=#0000bb> 8 characters</font>\n"
"    or longer. Please avoid using space, punctuation marks and non ASCII characters.<br>\n"
"    You may use the _ (underscore) - (minus) sign + (plus) sign.\n"
"    <tr><td colspan=2 align=center>\n"
"        <table align=center border=0 width=100%  frame=void>\n"
"            <tr><td colspan=3 width=100%>\n"
"                    <tr bgcolor=#eeeeee><td align=center>\n"
"                    <div style=\"font-size:large\" align=center>\n"
"                    <b>New Web Login Credentials:</b><br>\n"
"                    </div>\n"
"        </table>\n"
"        <tr><td>\n"
"        <tr> <td align=right>\n"
"    Station name:  &nbsp<td width=50%><input id=apname name=apname type=text\n"
"                        autofocus value=hnamehnamehnamehnamehnamehnamehname>\n"
"        <tr><td align=right>\n"
"    Station password:  &nbsp<td><input name=appass type=password\n"
"                        value=pass1pass1pass1pass1pass1pass1>\n"
"        <tr><td align=right>\n"
"    Repeat password:  &nbsp<td><input name=appass2 type=password\n"
"                        value=pass2pass2pass2pass2pass2pass2>\n"
"    <tr><td colspan=3>\n"
"    <hr>\n"
"    <tr> <td> <td colspan=2>\n"
"        <input type=button onclick=save_wifi() id=netbutt name=netbutt accesskey=c\n"
"        value='Save Web Configuration'>\n"
"                        <font style=color:#aaaaaa>(Alt+Shift+c)</font>\n"
"    <tr> <td colspan=3 align=center>\n"
"</table>\n"
"<center><code>\n"
"            | WiFi FCC-ID: 2AC7Z-ESPS2MINI1 | LoRA FCC-ID: 2BCKU-RA0212 |\n"
"    </code>\n"
"<tr><td>\n"
"  <table width=100% border=0>\n"
"        <tr>\n"
"            <td align=center colspan=3 width=100%>\n"
"            <hr>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_4.html> Main Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_2.html> WiFi Settings </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                 <div style=\"font-size:large\"   align=center>\n"
"                    <a href=page_3.html> LORA Parameters </a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                    <a href=page_8.html> Quick Start Manual </a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html> Back to Home Page </a>\n"
"                </div>\n"
"           <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html?reboot=true>Reboot Device</a>\n"
"                </div>\n"
"    </table>\n"
"    <tr>\n"
"    <td colspan=2 align=center>\n"
"    <hr>\n"
"    <!--<tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <a href=page_1.html?home=true>Back to Home Page</a>\n"
"        </div>\n"
"    -->\n"
"    <tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:small\">\n"
"            ID (Main) (Mac Address): macmacmacmacmacmacmac<br>\n"
"            Current Boot Count:  bcountbcount<br>\n"
"            Software Version / Build Date: softversoftversoftversoftversoftversoftver<br>\n"
"        </div>\n"
"    <tr><td colspan=2 align=center>\n"
"        Peter Glen, (C) 2026 <br>\n"
"    <tr><td colspan=2 align=center>\n"
"</table>\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
// EOF
