
/* =====[ ESP32 project ]=================================================

   File Name:       main/html/page_3.html

   Description:     Main file

   Revisions:       (for the original file)

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  Wed, 11-03-26   Peter Glen      Initial version.

   ======================================================================= */

// Page contents as header. DO NOT EDIT. Contents are overwritten at
// compile time.
// Edit the corresponding HTML file instead: main/html/page_3.html

const char lora_html [] =

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n"
"<html>\n"
"<head>\n"
"<title>LORA WiFi LORA Configuration Page</title>\n"
"<meta charset=\"UTF-8\">\n"
"<link rel='icon' href='data:;base64,iVBORw0KGgo='>\n"
"</head>\n"
"<body>\n"
"<form method=post id=myform>\n"
"<table align=center border=0 width=800 frame=void>\n"
"<style>\n"
".container {\n"
"	text-align: left;\n"
"	border: 1px solid green;\n"
"	padding: 5px;\n"
"    }\n"
".container table {\n"
"	border: 1px solid red;\n"
"    margin: 0 auto;\n"
"    }\n"
".chris {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      45px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2a  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    display:        inline-block;\n"
"    }\n"
".chris2b  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris2c  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      25px;\n"
"    font-style:     bold;\n"
"    }\n"
".chris3  {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    font-size:      16px;\n"
"    }\n"
".myDiv {\n"
"  font-size: 100px;\n"
"  text-align: center;\n"
"}\n"
"html, address, blockquote, body, dd, div, dl, dt, fieldset,\n"
"form, h1, h2, h3, h4, h5, h6, noframes, ol, p, ul, center,\n"
"dir, hr, menu, pre {\n"
"    font-family:    Arial, Helvetica, sans-serif;\n"
"    }\n"
".mydiv {\n"
"    /*background:yellow;\n"
"    color:blue;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    display:inline-block;\n"
"    */\n"
"    vertical-align:top;\n"
"    horizontal-align:right;\n"
"}\n"
"textarea {\n"
"    border-color:#eeeeee;\n"
"    width:90%;\n"
"}\n"
".mytext {\n"
"    /*background:yellow;\n"
"    color:blue;*/\n"
"    width:100%;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:#eeeeee;\n"
"    display:inline-block;\n"
"}\n"
"</style>\n"
" <tr><td>\n"
"    <table width=100% border=0>\n"
"    <tr bgcolor=#eeeeee><td align=center>\n"
"    <a href=page_1.html?home=true style=\"text-decoration: none; color: black;\">\n"
"        <div class=\"chris\" align=center>\n"
"            LORA WiFi Transceiver\n"
"        </div>\n"
"    </a>\n"
"    </table>\n"
"    <tr><td>\n"
"    <table align=center>\n"
"        <tr><td>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <font color=#0000ff>\n"
"            StatusStatusStatusStatusStatusStatusStatusStatus\n"
"            </font>\n"
"        </div>\n"
"    </table>\n"
"<script async>\n"
"    //console.log(\"Start LORA\n\");\n"
"    const isNumeric2 = (str) => Number.isFinite(+str);\n"
"    function check_lims(data, validx, lower, upper) {\n"
"        valx = data.get(validx)\n"
"        if (!isNumeric2(valx))\n"
"            {\n"
"            alert(\"Field: \" + validx + \" must be a number.\")\n"
"            return;\n"
"            }\n"
"        //console.log(\"value: %s\", valx);\n"
"        if (valx < lower || valx > upper)\n"
"            {\n"
"            alert(\"Number out of range for:  \" + validx + \" value = \" + valx)\n"
"            return;\n"
"            }\n"
"        }\n"
"    function save_lora() {\n"
"        //console.log(\"Save LORA\n\");\n"
"        const formData = new FormData(myform);\n"
"        console.log(\"Data\", formData);\n"
"        check_lims(formData, \"spread\", 1, 12);\n"
"        check_lims(formData, \"bwidth\", 10, 500);\n"
"        check_lims(formData, \"txfreq\", 433.05, 434.79);\n"
"    }\n"
"</script>\n"
"<table width=100%>\n"
"    <tr><td colspan=2 align=center height=12>\n"
"    The following fields determine the LORA transmit / receive configuration.\n"
"    These configurations must match between the sender and receiver units.\n"
"    The parameters are range contained. The frequency parameter is a floating\n"
"    point number multiplied by megahertz.\n"
"    The bandwidth parameter is a floating point number multiplied by kilohertz.\n"
"    <tr><td colspan=2 align=center>\n"
"        <table align=center border=0 width=100%  frame=void>\n"
"            <tr><td colspan=3 width=100%>\n"
"                    <tr bgcolor=#eeeeee><td align=center>\n"
"                    <div style=\"font-size:large\" align=center>\n"
"                    <b>LORA parameters:</b><br>\n"
"                    </div>\n"
"        </table>\n"
"        <tr><td>\n"
"        <tr> <td align=right>\n"
"            LORA Spread Factor: (1 - 12)  &nbsp<td width=50%><input name=spread type=text value=>\n"
"        <tr><td align=right>\n"
"            LORA Bandwidth: (10 - 500) &nbsp<td><input name=bwidth type=text  value=>\n"
"    <tr><td>\n"
"    <tr><td colspan=2 align=right>\n"
"        <table align=center border=0 width=100%  frame=void>\n"
"            <tr><td colspan=3 width=100%>\n"
"                    <tr bgcolor=#eeeeee><td align=center>\n"
"                    <div style=\"font-size:large\" align=center>\n"
"                    <b>Optional (advanced) LORA parameters:</b><br>\n"
"                    </div>\n"
"        </table>\n"
"    <tr><td>\n"
"    <tr> <td align=right>\n"
"        LORA TX power (1-12):  &nbsp<td><input name=txpower type=text value=>\n"
"    <tr> <td align=right>\n"
"        LORA Frequency: (433.05 - 434.79) &nbsp<td><input name=txfreq type=text value=>\n"
"    <tr><td>\n"
"    <tr> <td colspan=3 align=center>\n"
"    <input type=button onclick=save_lora() name=confbutt value='Save Configuration'>\n"
"    <tr> <td colspan=3 align=center>\n"
"</table>\n"
"<tr><td>\n"
"  <table width=100% border=0>\n"
"        <tr>\n"
"            <td align=center colspan=2 width=100%>\n"
"            <hr>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\"   align=center>\n"
"                   <a href=page_2.html>Settings</a>\n"
"                </div>\n"
"            <td align=center>\n"
"                 <div style=\"font-size:large\"   align=center>\n"
"                    <a href=page_3.html> LORA Parameters</a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                    <a href=page_8.html> Quick Start Manual</a>\n"
"                </div>\n"
"            <td align=center>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html?reboot=true>Reboot Device</a>\n"
"                </div>\n"
"        <tr>\n"
"            <td align=center colspan=2>\n"
"                <div style=\"font-size:large\" >\n"
"                   <a href=page_1.html>Back to Home Page</a>\n"
"                </div>\n"
"    </table>\n"
"    <tr>\n"
"    <td colspan=2 align=center>\n"
"    <hr>\n"
"    <!--<tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:large\" align=center>\n"
"            <a href=page_1.html?home=true>Back to Home Page</a>\n"
"        </div>\n"
"    -->\n"
"    <tr><td colspan=2 align=center>\n"
"        <div style=\"font-size:small\">\n"
"            ID (Main) (Mac Address): macmacmacmacmacmacmac<br>\n"
"            Current Boot Count:  bcountbcount<br>\n"
"            Software Version / Build Date: softversoftversoftversoftversoftversoftver<br>\n"
"        </div>\n"
"    <tr><td colspan=2 align=center>\n"
"        Peter Glen, (C) 2026 <br>\n"
"    <tr><td colspan=2 align=center>\n"
"</table>\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
// EOF
